name: mechfind
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.9.0
  supabase: ^2.8.0
  google_maps_flutter: ^2.12.3
  location: ^8.0.1
  cached_network_image: ^3.3.1

  url_launcher: ^6.3.2
  flutter_polyline_points: ^2.0.0
  flutter_map: ^8.2.1
  flutter_map_location_marker: ^10.1.0

  

  latlong2: ^0.9.1


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  

 
  # For tracking and maps

  # For making phone calls
  
  # For storing user data
  shared_preferences: ^2.2.2
  # For image handling
  
  # For HTTP requests
  http: ^1.4.0
  # For date formatting
  intl: ^0.18.1



  fl_chart: ^1.0.0
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.8
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  flutter_rating_bar: ^4.0.1
  


  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png
    - zob_assets/
    - assets/landing_bg.png
